"""Chinese approval explanations for Hermes dangerous-command prompts."""

from __future__ import annotations

import base64
import json
import os
import queue
import re
import shlex
import shutil
import subprocess
import sys
import threading
import time
from collections import OrderedDict
from datetime import datetime
from pathlib import Path
from typing import Any


MAX_CACHE_ITEMS = 64
MAX_MESSAGE_CHARS = 500
MAX_COMMAND_CHARS = 1200
MAX_ARG_CHARS = 800
PLUGIN_DIR = Path(__file__).resolve().parent
CONFIG_PATH = PLUGIN_DIR / "config.yaml"
LOG_PATH = Path.home() / ".hermes" / "logs" / "approval-explainer.jsonl"

DEFAULT_CONFIG = {
    "language": "简体中文",
    "bullet_count": "3-5",
    "max_bullet_chars": 45,
    "max_tokens": 260,
    "temperature": 0.1,
    "timeout": 8,
    "llm_wall_timeout": 8,
    "provider": "",
    "model": "",
    "provider_extra_body": {
        "xiaomi": {
            "thinking": {"type": "disabled"},
            "top_p": 0.95,
        },
    },
    "include_session_metadata": False,
    "skip_repeated_after_accept": True,
    "print_to_stderr": True,
    "desktop_notification": {
        "enabled": True,
        "title": "Hermes 请求授权",
        "open_url": "hermes://",
        "message_chars": None,
        "fallback_to_stderr": True,
        "macos": {
            "prefer_terminal_notifier": True,
            "activate_bundle_id": "com.nousresearch.hermes",
        },
        "windows": {
            "prefer_burnt_toast": True,
            "toast_app_logo": "assets/hermes-logo.png",
        },
    },
}

_turn_cache: OrderedDict[str, dict[str, Any]] = OrderedDict()
_assistant_action_cache: OrderedDict[str, dict[str, Any]] = OrderedDict()
_tool_cache: OrderedDict[str, dict[str, Any]] = OrderedDict()
_accepted_explanation_keys: set[str] = set()
_pending_explanation_keys: dict[str, str] = {}
_last_explanation: dict[str, Any] | None = None
_ACCEPT_CHOICES = {"once", "session", "always"}


RISK_DICTIONARY = {
    "rm_rf": {
        "label": "递归强制删除",
        "risk": "高",
        "meaning": "可能删除目录及其全部内容，删除后通常不能从文件系统直接恢复。",
        "check": "确认路径是否正确，是否有备份，是否只是可重新生成的构建产物。",
    },
    "sudo": {
        "label": "管理员权限",
        "risk": "高",
        "meaning": "命令会请求系统级权限，可能修改系统配置、权限或受保护文件。",
        "check": "确认命令来源可信，并理解它会修改哪些系统资源。",
    },
    "curl_pipe_sh": {
        "label": "下载并执行脚本",
        "risk": "高",
        "meaning": "可能把网络上的脚本直接交给 shell 执行，脚本内容可能变化且难以审计。",
        "check": "优先先下载查看脚本内容，确认来源和校验和。",
    },
    "git_push_force": {
        "label": "强制推送",
        "risk": "高",
        "meaning": "可能改写远端 Git 历史，影响协作者和 CI 状态。",
        "check": "确认目标分支、远端仓库，以及是否已经和协作者同步。",
    },
    "chmod_recursive": {
        "label": "递归修改权限",
        "risk": "中高",
        "meaning": "可能批量改变文件权限，导致文件暴露、脚本可执行或服务无法访问。",
        "check": "确认权限值和作用路径，避免作用到项目根目录或家目录。",
    },
    "chown_recursive": {
        "label": "递归修改所有者",
        "risk": "中高",
        "meaning": "可能批量改变文件所有者，导致服务、构建或用户权限异常。",
        "check": "确认用户/组和作用路径是否正确。",
    },
}


def register(ctx):
    ctx.register_hook("pre_llm_call", _capture_turn_context)
    ctx.register_hook("post_api_request", _capture_assistant_action_context)
    ctx.register_hook("pre_tool_call", _capture_tool_call)
    ctx.register_hook(
        "pre_approval_request",
        lambda **kwargs: _explain_approval_request(ctx, **kwargs),
    )
    ctx.register_hook("post_approval_response", _record_approval_response)
    ctx.register_command(
        name="approval-explainer-last",
        handler=_last_explanation_command,
        description="Show the most recent approval explanation generated by approval-explainer.",
    )


def _capture_turn_context(
    session_id: str = "",
    user_message: str = "",
    model: str = "",
    provider: str = "",
    platform: str = "",
    **kwargs,
):
    key = _cache_key(session_id=session_id, **kwargs)
    _remember(
        _turn_cache,
        key,
        {
            "user_message": _redact_and_truncate(user_message, MAX_MESSAGE_CHARS),
            "provider": _redact_and_truncate(provider, 80),
            "model": _redact_and_truncate(model, 120),
        },
    )
    return None


def _capture_assistant_action_context(
    session_id: str = "",
    task_id: str = "",
    assistant_message: Any = None,
    model: str = "",
    platform: str = "",
    finish_reason: str = "",
    **kwargs,
):
    """Cache the model text/reasoning that immediately preceded tool calls."""
    key = _cache_key(session_id=session_id, task_id=task_id, **kwargs)
    content = _message_attr(assistant_message, "content", "")
    reasoning = (
        _message_attr(assistant_message, "reasoning", "")
        or _message_attr(assistant_message, "reasoning_content", "")
        or _message_attr(assistant_message, "reasoning_details", "")
    )
    tool_calls = _normalize_tool_calls(_message_attr(assistant_message, "tool_calls", []))
    if not content and not reasoning and not tool_calls:
        return None

    _remember(
        _assistant_action_cache,
        key,
        {
            "assistant_content_before_tool": _redact_and_truncate(
                _stringify_text(content), MAX_MESSAGE_CHARS
            ),
            "assistant_reasoning_before_tool": _redact_and_truncate(
                _stringify_text(reasoning), MAX_MESSAGE_CHARS
            ),
            "assistant_tool_calls": tool_calls,
        },
    )
    return None


def _capture_tool_call(
    tool_name: str = "",
    args: dict | None = None,
    task_id: str = "",
    session_id: str = "",
    **kwargs,
):
    key = _cache_key(session_id=session_id, task_id=task_id, **kwargs)
    _remember(
        _tool_cache,
        key,
        {
            "tool_name": tool_name,
            "args": _safe_json(args or {}, max_chars=MAX_ARG_CHARS),
        },
    )
    return None


def _explain_approval_request(
    ctx,
    command: str,
    description: str,
    pattern_key: str = "",
    pattern_keys: list[str] | None = None,
    session_key: str = "",
    surface: str = "",
    **kwargs,
):
    started = time.monotonic()
    pattern_keys = list(pattern_keys or ([pattern_key] if pattern_key else []))
    key = _cache_key(session_id=session_key, **kwargs)
    turn_context = _turn_cache.get(key) or _latest_value(_turn_cache)
    assistant_action_context = _match_assistant_action_context(key, command)
    tool_context = _match_tool_context(key, command)
    config = _load_config()
    explanation_key = _explanation_key(session_key, command, pattern_keys)
    approval_id = _approval_identity(session_key, command, pattern_keys)
    if config["skip_repeated_after_accept"] and explanation_key in _accepted_explanation_keys:
        _write_log(
            "pre_approval_explanation_skipped",
            {
                "timestamp": datetime.now().isoformat(timespec="seconds"),
                "command": command,
                "description": description,
                "pattern_key": pattern_key,
                "pattern_keys": pattern_keys,
                "surface": surface,
                "session_key": session_key,
                "explanation_key": explanation_key,
                "reason": "previously accepted in this plugin session",
            },
        )
        return None

    _pending_explanation_keys[approval_id] = explanation_key
    facts = _compact_facts(
        command=command,
        description=description,
        pattern_keys=pattern_keys,
        surface=surface,
        session_key=session_key,
        turn_context=turn_context,
        assistant_action_context=assistant_action_context,
        tool_context=tool_context,
        include_session_metadata=bool(config["include_session_metadata"]),
    )

    explanation = _fallback_explanation(facts)
    llm_error = None
    text, llm_error, llm_meta = _complete_explanation_with_wall_timeout(
        ctx, facts, config, turn_context
    )
    if text:
        explanation = text

    payload = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "command": command,
        "description": description,
        "pattern_key": pattern_key,
        "pattern_keys": pattern_keys,
        "surface": surface,
        "session_key": session_key,
        "explanation": explanation,
        "llm_error": llm_error,
        "llm_request": llm_meta,
        "model_action_context": assistant_action_context,
        "elapsed_ms": int((time.monotonic() - started) * 1000),
    }
    notification = _send_desktop_notification(
        explanation=explanation,
        command=command,
        description=description,
        config=config,
    )
    payload["notification"] = notification
    _set_last_explanation(payload)
    _write_log("pre_approval_explanation", payload)
    notification_cfg = _desktop_notification_config(config)
    should_fallback_to_stderr = (
        notification.get("status") != "disabled"
        and not notification.get("ok")
        and notification_cfg.get("fallback_to_stderr")
    )
    if config["print_to_stderr"] or should_fallback_to_stderr:
        _display_explanation(explanation, surface)
    return None


def _complete_explanation_with_wall_timeout(
    ctx,
    facts: dict[str, Any],
    config: dict[str, Any],
    turn_context: dict[str, Any] | None,
) -> tuple[str | None, str | None, dict[str, Any]]:
    """Cap approval latency even when Hermes' auxiliary fallback chain is slow."""
    wall_timeout = _positive_float(config.get("llm_wall_timeout"), fallback=8.0)
    extra_body, llm_meta = _provider_extra_body(config, turn_context)
    messages = _explanation_messages(facts, config)
    result_queue: queue.Queue[tuple[str | None, str | None, dict[str, Any]]] = queue.Queue(maxsize=1)

    def worker() -> None:
        try:
            if extra_body:
                result = _complete_with_extra_body(ctx, messages, config, extra_body)
            else:
                result = ctx.llm.complete(
                    messages=messages,
                    max_tokens=int(config["max_tokens"]),
                    temperature=float(config["temperature"]),
                    timeout=int(config["timeout"]),
                    provider=config["provider"] or None,
                    model=config["model"] or None,
                    purpose="approval-explainer.pre_approval_request",
                )
            text = result.text.strip() if getattr(result, "text", None) else None
            result_queue.put_nowait((text, None, llm_meta))
        except Exception as exc:
            result_queue.put_nowait((None, f"{type(exc).__name__}: {exc}", llm_meta))

    thread = threading.Thread(
        target=worker,
        name="approval-explainer-llm",
        daemon=True,
    )
    thread.start()
    try:
        return result_queue.get(timeout=wall_timeout)
    except queue.Empty:
        return None, f"TimeoutError: explanation LLM exceeded {wall_timeout:.1f}s wall timeout", llm_meta


def _explanation_messages(facts: dict[str, Any], config: dict[str, Any]) -> list[dict[str, str]]:
    return [
        {
            "role": "system",
            "content": (
                f"你是 Hermes 的授权说明助手。用{config['language']}，面向不懂命令行的用户。"
                "只基于输入事实，解释：为什么 agent 要调用这个工具、为什么 Hermes 判定危险、"
                "用户批准前应检查什么。不要决定是否批准，不要说命令已经执行。"
                f"输出 {config['bullet_count']} 条短项目符号，每条不超过 "
                f"{config['max_bullet_chars']} 个字符。"
            ),
        },
        {
            "role": "user",
            "content": (
                "请简短解释这次授权请求：\n"
                + json.dumps(facts, ensure_ascii=False, indent=2)
            ),
        },
    ]


def _provider_extra_body(
    config: dict[str, Any],
    turn_context: dict[str, Any] | None,
) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    provider = str(config.get("provider") or (turn_context or {}).get("provider") or "").strip().lower()
    model = str(config.get("model") or (turn_context or {}).get("model") or "").strip().lower()
    if not provider and model.startswith("mimo"):
        provider = "xiaomi"
    provider_extra = config.get("provider_extra_body")
    if not isinstance(provider_extra, dict):
        return None, {"provider": provider, "model": model, "extra_body": "disabled"}
    extra = provider_extra.get(provider)
    if not isinstance(extra, dict) or not extra:
        return None, {"provider": provider, "model": model, "extra_body": "not_configured"}
    body = _merge_config_value({}, extra)
    if provider == "xiaomi" and "max_completion_tokens" not in body:
        body["max_completion_tokens"] = int(config["max_tokens"])
    return body, {
        "provider": provider,
        "model": model,
        "extra_body": "provider_scoped",
        "extra_body_keys": sorted(body.keys()),
    }


def _complete_with_extra_body(
    ctx,
    messages: list[dict[str, str]],
    config: dict[str, Any],
    extra_body: dict[str, Any],
):
    """Use Hermes' auxiliary client only for provider-scoped request extras.

    The public plugin LLM API does not expose extra_body yet. This path is kept
    narrow so non-MiMo providers continue using ctx.llm.complete unchanged.
    """
    from agent.auxiliary_client import call_llm
    from agent.plugin_llm import _check_overrides

    policy = ctx.llm._policy_loader(ctx.llm._plugin_id)
    provider, model, _, _ = _check_overrides(
        policy,
        requested_provider=config["provider"] or None,
        requested_model=config["model"] or None,
        requested_agent_id=None,
        requested_profile=None,
    )

    response = call_llm(
        task=None,
        provider=provider,
        model=model,
        messages=messages,
        temperature=float(config["temperature"]),
        max_tokens=int(config["max_tokens"]),
        timeout=int(config["timeout"]),
        extra_body=extra_body,
    )

    class Result:
        pass

    result = Result()
    result.text = _extract_llm_text(response)
    return result


def _extract_llm_text(response: Any) -> str:
    try:
        return response.choices[0].message.content or ""
    except Exception:
        return ""


def _positive_float(value: Any, fallback: float) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return fallback
    return parsed if parsed > 0 else fallback


def _compact_facts(
    command: str,
    description: str,
    pattern_keys: list[str],
    surface: str,
    session_key: str,
    turn_context: dict[str, Any] | None,
    assistant_action_context: dict[str, Any] | None,
    tool_context: dict[str, Any] | None,
    include_session_metadata: bool,
) -> dict[str, Any]:
    action_context = assistant_action_context or {}
    reason = (
        action_context.get("assistant_content_before_tool")
        or action_context.get("assistant_reasoning_before_tool")
        or ""
    )
    facts = {
        "command": _redact_and_truncate(command, MAX_COMMAND_CHARS),
        "hermes_risk": description,
        "pattern_keys": pattern_keys,
        "cwd": os.getcwd(),
        "user_request": (turn_context or {}).get("user_message", ""),
        "model_intent": reason,
        "tool_call": _summarize_tool_call(action_context, tool_context),
        "risks": [_risk_summary(key) for key in pattern_keys],
        "paths": _path_summaries(command),
    }
    if include_session_metadata:
        facts["surface"] = surface
        facts["session_key"] = session_key
    return facts


def _record_approval_response(
    command: str,
    description: str,
    pattern_key: str = "",
    pattern_keys: list[str] | None = None,
    session_key: str = "",
    surface: str = "",
    choice: str = "",
    **kwargs,
):
    normalized_patterns = list(pattern_keys or ([pattern_key] if pattern_key else []))
    approval_id = _approval_identity(session_key, command, normalized_patterns)
    explanation_key = _pending_explanation_keys.pop(approval_id, None)
    if choice in _ACCEPT_CHOICES:
        explanation_key = explanation_key or _explanation_key(
            session_key,
            command,
            normalized_patterns,
        )
        _accepted_explanation_keys.add(explanation_key)
    _write_log(
        "post_approval_response",
        {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "command": command,
            "description": description,
            "pattern_key": pattern_key,
            "pattern_keys": list(pattern_keys or []),
            "session_key": session_key,
            "surface": surface,
            "choice": choice,
            "explanation_key": explanation_key,
            "explanation_key_accepted": choice in _ACCEPT_CHOICES,
        },
    )
    return None


def _last_explanation_command(raw_args: str = "") -> str:
    del raw_args
    if not _last_explanation:
        return "还没有生成过 approval 解释。"
    return _last_explanation.get("explanation", "最近一次记录没有解释文本。")


def _display_explanation(text: str, surface: str) -> None:
    banner = "\n[approval-explainer] 授权前中文说明\n"
    body = text.strip()
    if surface == "cli" or not surface:
        print(banner + body + "\n", file=sys.stderr, flush=True)
    else:
        print(
            f"\n[approval-explainer:{surface}] 授权前中文说明\n{body}\n",
            file=sys.stderr,
            flush=True,
        )


def _send_desktop_notification(
    explanation: str,
    command: str,
    description: str,
    config: dict[str, Any],
) -> dict[str, Any]:
    notify_config = _desktop_notification_config(config)
    if not notify_config.get("enabled"):
        return {"ok": False, "status": "disabled"}

    title = str(notify_config.get("title") or "Hermes 请求授权")
    body = _notification_body(
        explanation=explanation,
        command=command,
        description=description,
        max_chars=_notification_message_limit(notify_config.get("message_chars")),
    )

    if sys.platform == "darwin":
        return _notify_macos(title, body, notify_config)
    if sys.platform.startswith("win"):
        return _notify_windows(title, body, notify_config)
    return {"ok": False, "status": "unsupported_platform", "platform": sys.platform}


def _desktop_notification_config(config: dict[str, Any]) -> dict[str, Any]:
    value = config.get("desktop_notification")
    return value if isinstance(value, dict) else {}


def _notification_body(
    explanation: str,
    command: str,
    description: str,
    max_chars: int | None,
) -> str:
    cleaned = re.sub(r"^\s*[-*]\s*", "", explanation.strip(), flags=re.MULTILINE)
    cleaned = re.sub(r"\s+", " ", cleaned)
    if not cleaned:
        cleaned = f"{description}: {command}"
    redacted = _redact_text(cleaned)
    if max_chars is None:
        return redacted
    return _truncate_text(redacted, max(60, max_chars))


def _notification_message_limit(value: Any) -> int | None:
    if value is None:
        return None
    if isinstance(value, str) and value.strip().lower() in {"", "auto", "full", "none", "null"}:
        return None
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def _notify_macos(title: str, body: str, config: dict[str, Any]) -> dict[str, Any]:
    macos_config = config.get("macos") if isinstance(config.get("macos"), dict) else {}
    notifier = shutil.which("terminal-notifier")
    if macos_config.get("prefer_terminal_notifier", True) and notifier:
        args = [notifier, "-title", title, "-message", body]
        bundle_id = str(macos_config.get("activate_bundle_id") or "").strip()
        open_url = str(config.get("open_url") or "").strip()
        if bundle_id:
            args.extend(["-activate", bundle_id])
        elif open_url:
            args.extend(["-open", open_url])
        result = _run_notification_command(args)
        if result["ok"]:
            result["method"] = "terminal-notifier"
            result["click_action"] = "activate_app" if bundle_id else "open_url"
            return result

    script = (
        f"display notification {_applescript_string(body)} "
        f"with title {_applescript_string(title)}"
    )
    result = _run_notification_command(["osascript", "-e", script])
    result["method"] = "osascript"
    result["click_action"] = "none"
    return result


def _notify_windows(title: str, body: str, config: dict[str, Any]) -> dict[str, Any]:
    powershell = shutil.which("powershell") or shutil.which("pwsh")
    if not powershell:
        return {"ok": False, "status": "missing_powershell"}

    windows_config = config.get("windows") if isinstance(config.get("windows"), dict) else {}
    open_url = str(config.get("open_url") or "").strip()
    use_burnt_toast = bool(windows_config.get("prefer_burnt_toast", True))
    toast_app_logo = _resolve_plugin_path(windows_config.get("toast_app_logo", ""))
    payload = base64.b64encode(
        json.dumps(
            {
                "title": title,
                "message": body,
                "open_url": open_url,
                "use_burnt_toast": use_burnt_toast,
                "toast_app_logo": toast_app_logo,
            },
            ensure_ascii=False,
        ).encode("utf-8")
    ).decode("ascii")
    script = r'''
$ErrorActionPreference = "Stop"
$PayloadJson = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("__PAYLOAD__"))
$Payload = $PayloadJson | ConvertFrom-Json
$Title = [string]$Payload.title
$Message = [string]$Payload.message
$OpenUrl = [string]$Payload.open_url
$UseBurntToast = [bool]$Payload.use_burnt_toast
$AppLogo = [string]$Payload.toast_app_logo
if ([string]::IsNullOrWhiteSpace($Message)) {
  $Message = "Hermes approval request"
}
if ($UseBurntToast -and (Get-Module -ListAvailable -Name BurntToast)) {
  Import-Module BurntToast
  $ClickAction = "none"
  $ProtocolRegistered = $false
  $ToastParams = @{ Text = @($Title, $Message) }
  if ($AppLogo -and (Test-Path $AppLogo)) {
    $ToastParams.AppLogo = $AppLogo
  }
  if ($OpenUrl) {
    try {
      $Scheme = ([System.Uri]$OpenUrl).Scheme
      $ProtocolKey = "Registry::HKEY_CLASSES_ROOT\$Scheme"
      if (Test-Path $ProtocolKey) {
        $ProtocolValue = (Get-ItemProperty -Path $ProtocolKey -Name "URL Protocol" -ErrorAction SilentlyContinue)
        $ProtocolRegistered = $null -ne $ProtocolValue
      }
    } catch {
      $ProtocolRegistered = $false
    }
  }
  if ($OpenUrl -and $ProtocolRegistered) {
    $button = New-BTButton -Content "Open Hermes" -Arguments $OpenUrl -ActivationType Protocol
    $ToastParams.Button = $button
    New-BurntToastNotification @ToastParams
    $ClickAction = "open_url_button"
  } else {
    New-BurntToastNotification @ToastParams
    if ($OpenUrl) {
      $ClickAction = "open_url_unregistered"
    }
  }
  Write-Output "method=burnt_toast"
  Write-Output "click_action=$ClickAction"
  if ($AppLogo -and (Test-Path $AppLogo)) {
    Write-Output "app_logo=custom"
  } else {
    Write-Output "app_logo=default"
  }
  exit 0
}
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$notify = New-Object System.Windows.Forms.NotifyIcon
$notify.Icon = [System.Drawing.SystemIcons]::Information
$notify.BalloonTipTitle = $Title
$notify.BalloonTipText = $Message
$notify.Visible = $true
$notify.ShowBalloonTip(10000)
Start-Sleep -Seconds 10
$notify.Dispose()
Write-Output "method=windows_balloon"
Write-Output "click_action=none"
'''.replace("__PAYLOAD__", payload)
    result = _run_notification_command(
        [
            powershell,
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-Command",
            script,
        ],
        timeout=15,
    )
    stdout = str(result.get("stdout") or "")
    if "method=burnt_toast" in stdout:
        result["method"] = "burnt_toast"
        result["click_action"] = _notification_stdout_value(stdout, "click_action") or "unknown"
    elif "method=windows_balloon" in stdout:
        result["method"] = "windows_balloon"
        result["click_action"] = _notification_stdout_value(stdout, "click_action") or "none"
    else:
        result["method"] = "powershell"
        result["click_action"] = "unknown"
    return result


def _notification_stdout_value(stdout: str, key: str) -> str:
    prefix = key + "="
    for line in stdout.splitlines():
        line = line.strip()
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
    return ""


def _resolve_plugin_path(value: Any) -> str:
    raw = str(value or "").strip()
    if not raw:
        return ""
    path = Path(raw).expanduser()
    if not path.is_absolute():
        path = PLUGIN_DIR / path
    return str(path)


def _run_notification_command(args: list[str], timeout: float = 5) -> dict[str, Any]:
    try:
        completed = subprocess.run(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
    except FileNotFoundError:
        return {"ok": False, "status": "missing_command", "command": Path(args[0]).name}
    except Exception as exc:
        return {"ok": False, "status": "error", "error": f"{type(exc).__name__}: {exc}"}
    result = {
        "ok": completed.returncode == 0,
        "status": "sent" if completed.returncode == 0 else "failed",
        "returncode": completed.returncode,
    }
    stdout = (completed.stdout or "").strip()
    stderr = (completed.stderr or "").strip()
    if stdout:
        result["stdout"] = _redact_and_truncate(stdout, 500)
    if stderr:
        result["stderr"] = _redact_and_truncate(stderr, 500)
    return result


def _applescript_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _fallback_explanation(facts: dict[str, Any]) -> str:
    risks = facts.get("risks") or []
    risk_text = "；".join(risk.get("summary", "") for risk in risks if risk.get("summary"))
    check_text = "；".join(dict.fromkeys(risk.get("check", "") for risk in risks if risk.get("check")))
    path_text = "；".join(facts.get("paths") or [])
    return "\n".join(
        [
            f"- 目的：{facts.get('model_intent') or '未捕获到明确说明'}",
            f"- 调用：{facts.get('tool_call') or facts.get('command')}",
            f"- 风险：{risk_text or facts.get('hermes_risk') or '命中高危规则'}",
            f"- 影响：{path_text or '未识别到具体路径'}",
            f"- 检查：{check_text or '确认命令、路径和是否可回滚'}",
        ]
    )


def _load_config() -> dict[str, Any]:
    config = DEFAULT_CONFIG.copy()
    if not CONFIG_PATH.exists():
        return config
    try:
        import yaml

        loaded = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8")) or {}
    except Exception as exc:
        _write_log(
            "config_error",
            {
                "timestamp": datetime.now().isoformat(timespec="seconds"),
                "error": f"{type(exc).__name__}: {exc}",
            },
        )
        return config

    if not isinstance(loaded, dict):
        return config
    for key in config:
        if key in loaded:
            config[key] = _merge_config_value(config[key], loaded[key])
    return config


def _merge_config_value(default: Any, loaded: Any) -> Any:
    if isinstance(default, dict) and isinstance(loaded, dict):
        merged = default.copy()
        for key, value in loaded.items():
            merged[key] = _merge_config_value(merged.get(key), value)
        return merged
    return loaded


def _risk_summary(key: str) -> dict[str, str]:
    risk = RISK_DICTIONARY.get(key, _unknown_risk(key))
    return {
        "key": key,
        "summary": f"{risk['label']}({risk['risk']}): {risk['meaning']}",
        "check": risk["check"],
    }


def _summarize_tool_call(
    action_context: dict[str, Any],
    tool_context: dict[str, Any] | None,
) -> str:
    calls = action_context.get("assistant_tool_calls") or []
    if calls:
        call = calls[0]
        return f"{call.get('name')} {call.get('arguments_preview')}"
    if tool_context:
        return f"{tool_context.get('tool_name')} {tool_context.get('args')}"
    return ""


def _path_summaries(command: str) -> list[str]:
    return [_path_summary(path) for path in _extract_paths(command)[:4]]


def _explanation_key(session_key: str, command: str, pattern_keys: list[str]) -> str:
    patterns = ",".join(sorted(pattern_keys))
    verb = _command_verb(command)
    paths = ",".join(_normalized_paths(command))
    if paths:
        normalized = f"{verb}|{paths}"
    else:
        normalized = _normalize_command_text(command)
    return f"{session_key or 'default'}|{patterns}|{normalized}"


def _approval_identity(session_key: str, command: str, pattern_keys: list[str]) -> str:
    patterns = ",".join(sorted(pattern_keys))
    return f"{session_key or 'default'}|{patterns}|{_normalize_command_text(command)}"


def _command_verb(command: str) -> str:
    try:
        tokens = shlex.split(command)
    except ValueError:
        tokens = command.split()
    return Path(tokens[0]).name if tokens else ""


def _normalized_paths(command: str) -> list[str]:
    paths = []
    for raw_path in _extract_paths(command)[:4]:
        path = Path(os.path.expanduser(raw_path))
        if not path.is_absolute():
            path = Path.cwd() / path
        paths.append(str(path.resolve()))
    return paths


def _normalize_command_text(command: str) -> str:
    try:
        tokens = shlex.split(command)
    except ValueError:
        tokens = command.split()
    return " ".join(tokens)


def _path_summary(raw_path: str) -> str:
    path = Path(os.path.expanduser(raw_path))
    if not path.is_absolute():
        path = Path.cwd() / path
    path = path.resolve()
    if not path.exists():
        return f"{path}: 路径不存在"

    if path.is_file():
        return f"{path}: 文件，{path.stat().st_size} bytes"

    if path.is_dir():
        file_count, dir_count = _count_tree(path, limit=5000)
        return f"{path}: 目录，采样 {file_count} 文件/{dir_count} 子目录"

    return f"{path}: 存在，但不是普通文件或目录"


def _extract_paths(command: str) -> list[str]:
    try:
        tokens = shlex.split(command)
    except ValueError:
        tokens = command.split()

    paths = []
    skip_next = False
    for token in tokens[1:]:
        if skip_next:
            skip_next = False
            continue
        if token in {"-C", "-o", "--output", "-f", "--file"}:
            skip_next = True
            continue
        if token.startswith("-"):
            continue
        if any(mark in token for mark in ["/", ".", "~"]) and not re.match(r"^https?://", token):
            paths.append(token.rstrip(";"))
    return list(dict.fromkeys(paths))


def _count_tree(path: Path, limit: int) -> tuple[int, int]:
    files = 0
    dirs = 0
    try:
        for child in path.rglob("*"):
            if child.is_dir():
                dirs += 1
            elif child.is_file():
                files += 1
            if files + dirs >= limit:
                break
    except Exception:
        pass
    return files, dirs


def _match_assistant_action_context(key: str, command: str) -> dict[str, Any] | None:
    direct = _assistant_action_cache.get(key)
    if direct and _action_context_mentions_command(direct, command):
        return direct
    for value in reversed(_assistant_action_cache.values()):
        if _action_context_mentions_command(value, command):
            return value
    return direct or _latest_value(_assistant_action_cache)


def _action_context_mentions_command(context: dict[str, Any], command: str) -> bool:
    command_prefix = command[:80]
    if not command_prefix:
        return False
    return command_prefix in json.dumps(context, ensure_ascii=False, default=str)


def _match_tool_context(key: str, command: str) -> dict[str, Any] | None:
    direct = _tool_cache.get(key)
    if direct and command[:80] in json.dumps(direct, ensure_ascii=False):
        return direct
    for value in reversed(_tool_cache.values()):
        if command[:80] in json.dumps(value, ensure_ascii=False):
            return value
    return direct or _latest_value(_tool_cache)


def _normalize_tool_calls(tool_calls: Any) -> list[dict[str, str]]:
    normalized = []
    if not tool_calls:
        return normalized
    for tool_call in tool_calls:
        function = _message_attr(tool_call, "function", None)
        name = _message_attr(function, "name", "") if function is not None else _message_attr(tool_call, "name", "")
        arguments = (
            _message_attr(function, "arguments", "")
            if function is not None
            else _message_attr(tool_call, "arguments", "")
        )
        normalized.append(
            {
                "id": str(_message_attr(tool_call, "id", "")),
                "name": str(name),
                "arguments_preview": _redact_and_truncate(
                    _stringify_text(arguments), MAX_ARG_CHARS
                ),
            }
        )
    return normalized


def _message_attr(value: Any, name: str, default: Any = None) -> Any:
    if isinstance(value, dict):
        return value.get(name, default)
    return getattr(value, name, default)


def _stringify_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False, default=str)


def _remember(cache: OrderedDict[str, dict[str, Any]], key: str, value: dict[str, Any]) -> None:
    cache[key] = value
    cache.move_to_end(key)
    while len(cache) > MAX_CACHE_ITEMS:
        cache.popitem(last=False)


def _latest_value(cache: OrderedDict[str, dict[str, Any]]) -> dict[str, Any] | None:
    if not cache:
        return None
    return next(reversed(cache.values()))


def _cache_key(session_id: str = "", task_id: str = "", **kwargs) -> str:
    return (
        session_id
        or task_id
        or str(kwargs.get("session_key") or "")
        or str(kwargs.get("task_id") or "")
        or "default"
    )


def _safe_json(value: Any, max_chars: int) -> str:
    return _redact_and_truncate(json.dumps(value, ensure_ascii=False, default=str), max_chars)


def _redact_and_truncate(text: str, max_chars: int) -> str:
    return _truncate_text(_redact_text(text), max_chars)


def _redact_text(text: str) -> str:
    redacted = str(text)
    redacted = re.sub(
        r"(?i)(api[_-]?key|token|secret|password|authorization)(['\"]?\s*[:=]\s*['\"]?)[^'\"\s,}]+",
        r"\1\2[REDACTED]",
        redacted,
    )
    redacted = re.sub(r"(?i)bearer\s+[a-z0-9._~+/=-]{12,}", "Bearer [REDACTED]", redacted)
    redacted = re.sub(r"\bsk-[A-Za-z0-9_-]{12,}\b", "sk-[REDACTED]", redacted)
    return redacted


def _truncate_text(text: str, max_chars: int) -> str:
    value = str(text)
    if len(value) <= max_chars:
        return value
    return value[:max_chars] + f"... [truncated {len(value) - max_chars} chars]"


def _unknown_risk(key: str) -> dict[str, str]:
    return {
        "label": key or "未知规则",
        "risk": "未知",
        "meaning": "Hermes 的危险命令检测命中了这个规则。",
        "check": "确认命令、路径、权限和是否可回滚。",
    }


def _write_log(event: str, payload: dict[str, Any]) -> None:
    try:
        LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with LOG_PATH.open("a", encoding="utf-8") as handle:
            handle.write(
                json.dumps({"event": event, **payload}, ensure_ascii=False, default=str)
                + "\n"
            )
    except Exception:
        pass


def _set_last_explanation(payload: dict[str, Any]) -> None:
    global _last_explanation
    _last_explanation = payload
